/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generadorqr;

/**
 *
 * @author Jess
 */
public class jifrPoliticasdePrivacidad extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifrPoliticasdePrivacidad
     */
    public jifrPoliticasdePrivacidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPoliticasdePrivacidad = new javax.swing.JTextArea();
        jlPoliticasdePrivacidad = new javax.swing.JLabel();
        jlRayas = new javax.swing.JLabel();
        btnAceptarTC = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jScrollPane1.setBorder(null);

        txtPoliticasdePrivacidad.setEditable(false);
        txtPoliticasdePrivacidad.setColumns(20);
        txtPoliticasdePrivacidad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPoliticasdePrivacidad.setRows(5);
        txtPoliticasdePrivacidad.setText("SEGURIDAD Y PRIVACIDAD\nLa información que se envíe a la Base de datos de JJQR  a través de formularios para completar datos en la \naplicación se regirá de conformidad con el siguiente texto. En ese sentido, como usuario de esta aplicacion, \nle  informamos  sobre  el uso que le damos a los datos que registre en el mismo, a fin que pueda decidir si \nquiere ingresar sus datos o no.\nLos datos recogidos a través de esta aplicación serán objeto de tratamiento automatizado e incorporados a\nlas correspondientes bases de datos o ficheros de los que el Museo es titular y responsable.\nNombre,  dirección,  teléfono,  correo  electrónico,  entre  otros,  son  datos que nos permiten contactar a los\nusuarios  para resolver dudas, responder  a comentarios, almacenar  información,  que puedan interesar al\nadministrador.\nAl  facilitar sus  datos en la aplicación, nos está comunicando que Usted consciente, libre y voluntariamente\nnos  está  suministrando dicha  información  y  que además se encuentra de acuerdo con que dichos datos\npuedan ser trasmitidos y almacenados en la aplicación.\nEl Museo se compromete no divulgar sus datos. Únicamente podrá utilizarlos para los fines aquí descritos.\n\nUSTED RECONOCE Y ACEPTA QUE:\n\n•  Ha leído y acepta los términos y condiciones de uso descritos anteriormente.\n•  El uso  de  la  aplicación  JJQR  y  acceso a los contenidos en la misma corren por la cuenta y riesgo del\nadministrador o usuario que esté encargado de su manipulación.\n• En ningún caso las desarrolladoras de JJQR serán responsables de daño alguno derivado del uso de la\naplicación o de  la información  entregada hacia el público que acceda al Museo de la Escuela Isidro Ayora.\n");
        txtPoliticasdePrivacidad.setBorder(null);
        txtPoliticasdePrivacidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(txtPoliticasdePrivacidad);

        jlPoliticasdePrivacidad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPoliticasdePrivacidad.setText("Políticas de Privacidad");

        jlRayas.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        btnAceptarTC.setBackground(new java.awt.Color(51, 51, 51));
        btnAceptarTC.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarTC.setText("Aceptar");
        btnAceptarTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarTCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptarTC, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(283, 283, 283))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRayas)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jlPoliticasdePrivacidad)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlPoliticasdePrivacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlRayas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptarTC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarTCActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAceptarTCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarTC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlPoliticasdePrivacidad;
    private javax.swing.JLabel jlRayas;
    private javax.swing.JTextArea txtPoliticasdePrivacidad;
    // End of variables declaration//GEN-END:variables
}
